### PR TITLE
Docs data Update for 3.15.3

### PR DESCRIPTION
**Pull request by jokoho48**
**When merged this pull request will:**
- Update the Data for the Docs for 3.15.3
- Add Groups for the new Modules
- Fix some Internal Functions were marked as public functions
- Fix some issues with the make_docs script to work on Ubuntu 20.10

### CODE REVIEW

File: addons/ai/fnc_waypointGarrison.sqf [hunk 1]
```diff
@@ -1,6 +1,6 @@
 #include "script_component.hpp"
 /* ----------------------------------------------------------------------------
-Script: fnc_waypointGarrison
+Script: CBA_fnc_waypointGarrison
```
Comment (commy2) [inline addons/ai/fnc_waypointGarrison.sqf:3]: How many times do I have to reject this? It is not a function, but compiled as script by a waypoint via config entry. 

`CBA_fnc_waypointGarrison` does not exist. fnc_waypointGarrison.sqf does and it is only meant to be used as uncompiled script.

File: addons/xeh/fnc_supportMonitor.sqf [hunk 2]
```diff
@@ -1,6 +1,6 @@
 #include "script_component.hpp"
 /* ----------------------------------------------------------------------------
-Function: CBA_fnc_supportMonitor
+Internal Function: CBA_fnc_supportMonitor
```
Comment (commy2) [inline addons/xeh/fnc_supportMonitor.sqf:3]: This has uses for debugging too.

Comment (jokoho48) [reply addons/xeh/fnc_supportMonitor.sqf:3]: but it needs that tag to not show up in the Docs

File: addons/ai/fnc_waypointGarrison.sqf (hunk 1 above)
Comment (jokoho48) [reply addons/ai/fnc_waypointGarrison.sqf:3]: do we want to hide that from the Docs then? or what to do with it?

Comment (commy2) [reply addons/ai/fnc_waypointGarrison.sqf:3]: Hide it if you want, but it's no big deal. Do not name it "`CBA_fnc_waypointGarrison`" though, because that is not a thing.

File: addons/xeh/fnc_supportMonitor.sqf (hunk 2 above)
Comment (commy2) [reply addons/xeh/fnc_supportMonitor.sqf:3]: Why shouldn't it show up in the docs?

Comment (jokoho48) [reply addons/xeh/fnc_supportMonitor.sqf:3]: because in the Description it says "Internal use only." but i can just remove the Internal an it will show in the Docs

File: tools/make_docs [hunk 3]
```diff
@@ -1,38 +1,39 @@
 #!/bin/sh
```
Comment (Killswitch00) [inline tools/make_docs:2]: Add

```shopt -s xpg_echo```

to have Bash expand the escape sequences in echo. I tried that with dash (the default shell in Debian/Ubuntu) and everything still works.

File: addons/xeh/fnc_supportMonitor.sqf (hunk 2 above)
Comment (Killswitch00) [reply addons/xeh/fnc_supportMonitor.sqf:3]: So, internal or not? The description in this file does not mention "internal use only".

Comment (jokoho48) [reply addons/xeh/fnc_supportMonitor.sqf:3]: @Killswitch00 that was exactly my point.

Comment (Killswitch00) [reply addons/xeh/fnc_supportMonitor.sqf:3]: OK - to clarify, commy2 asked why it should not show up in the docs, to which you replied 'because in the Description it says "Internal use only"'

However, the description does not say "Internal use only", so it appears to me that the file was fine as it was. In other words: the CBA_fnc_supportMonitor function was visible in the documentation before this PR and should remain visible in the documentation.

Comment (jokoho48) [reply addons/xeh/fnc_supportMonitor.sqf:3]: oh damn, I was in the totally wrong function.

**Review by Killswitch00 — APPROVED** [review]
